repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1 #latest release version
    hooks:
      - id: codespell
        args: [--config=.codespellrc]
        files:  \.(rst|txt|md)$